version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wellify_test
      MYSQL_USER: snack_overflow
      MYSQL_PASSWORD: Ccgnx2024!
    ports:
      - "3306:3306"
    expose:
      - '3306'
    # command: ["sh", "-c", "mysql < /app/src/backend/database/seeds/setup.sql && ts-node /app/src/backend/database/seeds/runSeed.ts"]

